name = "navsphere"
compatibility_date = "2025-08-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_ID = "Ov23liB0qnz7T3V7pQsD"
GITHUB_OWNER = "leetone123"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navsphere-d2g.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://navsphere-d2g.pages.dev"

